### PR TITLE
Update dune-project

### PR DESCRIPTION
**Pull request by mseri**
Double check that dune correctly recognizes :post and generates the appropriate opam files

### CODE REVIEW

**Comment by pdarragh** [comment]
Wow, thanks so much for going to this effort, @mseri! I really appreciate it.

I'll incorporate the `:with-test` aspects from this suggestion, as well as the `package` stuff from your suggestion on #7. (I don't know why I didn't add the `package` field to all of the ppx_camlrack tests previously.) So I should be able to skip the `:post` designation part of this suggestion, if I'm reading your comments right.

I think it's interesting that Dune doesn't appear to support the `version` package variable used in dependencies. Even though I've got `(camlrack (= version))` in the `dune-project` file, it gets converted to `"camlrack" {= "version"}` in the generated `ppx_camlrack.opam` file when I run `dune build`. I guess I'll have to put together a workflow to make sure I don't forget to fix that each time I `opam publish`.

**Comment by mseri** [comment]
Ah good point. I think you need to write `:version` Otherwise it is interpreted as a string

**Comment by pdarragh** [comment]
Ah-ha! I don't see anything in Dune's stanza reference about just using `:` to create literals instead of strings, but perhaps I just missed it. But that change fixes the `version` issue!

I'm trying to do my due diligence and ensure everything works before re-pushing to opam. If I do `dune runtest -p camlrack`, everything works correctly. If I do `dune runtest -p ppx_camlrack` on its own, I get an error because `camlrack` isn't found:

```
$ dune runtest -p ppx_camlrack
File "ppx_camlrack/src/dune", line 4, characters 12-20:
4 |  (libraries camlrack ppxlib)
                ^^^^^^^^
Error: Library "camlrack" not found.
```

However, since `camlrack` is listed as a dependency in the `dune-project` file... is it the case that `camlrack` will be installed locally in the CI infrastructure prior to executing the `ppx_camlrack` tests? If I install `camlrack` first, everything works fine:

```
$ dune build @install -p camlrack
$ dune install camlrack
$ dune runtest -p ppx_camlrack
$ 
```

Is this the expected behavior? Or am I perhaps still missing some configuration?

**Comment by mseri** [comment]
This is to be expected. In the opam-repository CI you don’t see this since the code runs `opam install -t` For each package, ensuring that all the dependencies are pre-installed before running package specific builds and tests (somewhat equivalent to your build + install + runtest above)

**Comment by mseri** [comment]
You can make the GithubActions do these things for you by the way, using https://github.com/ocaml/setup-ocaml

**Comment by mseri** [comment]
I had a look at the changes you made, I think the package is good to be released

**Pull request closed without merging**
